rallpack 1 CI
CNS-OIST/STEPS4ModelRelease pull request #6
Opened 2022-04-05 14:41 UTC by cattabiani

Here we want to add all the scripts and stuff necessary to run rallpack 1 locally AND by the CI on bb5

2022-05-09 06:26 UTC, kotsaloscv requested changes
Other than nitpicking, LGTM!

2022-05-09 06:26 UTC, kotsaloscv commented on rallpack3/README.md
> +- Raw traces will appear in the result folder: `results/STEPS3`
I guess you mean here `raw_traces/` and not `results/` (other points as well)

2022-05-09 06:26 UTC, kotsaloscv commented on rallpack3/run.sbatch
> +spack load steps@develop
Maybe it would be better to spack load the hash from the CI, as I have it in my branch. See for example:
https://github.com/CNS-OIST/STEPS4ModelRelease/blob/37286a273508499355a8c920516f9fd18f9a5fc4/SimpleModel/profiling/strong_scaling.batch#L10

I think this is more clear and better for debugging in case in the future we have weird builds.

2022-05-09 06:26 UTC, kotsaloscv commented on validation/automated_validation_monitoring_results_displayer.ipynb
> +    "args =  f\"../../raw_traces/STEPS{steps_version} {ref_dir}\"\n",
if you are in the folder of the python file, do you need the `../../`? Thanks for clarifying.

2022-05-09 06:26 UTC, kotsaloscv commented on validation/automated_validation_monitoring_results_displayer.ipynb
> +      "python: can't open file '/gpfs/bbp.cscs.ch/ssd/gitlab_map_jobs/bbpcihpcproj12/J221382/hpc/HBP_STEPS/STEPS4ModelRelease/rallpack1/None.py': [Errno 2] No such file or directory\n"
You need to clean the output of the notebook and resave it :)

2022-05-09 08:10 UTC, cattabiani commented on rallpack3/README.md
> +- Raw traces will appear in the result folder: `results/STEPS3`
yes, I will change it

2022-05-09 08:11 UTC, cattabiani commented on rallpack3/README.md
> +- Raw traces will appear in the result folder: `results/STEPS3`
```suggestion
- Raw traces will appear in the result folder: `raw_traces/STEPS3`
```

2022-05-09 08:11 UTC, cattabiani commented on rallpack3/README.md
> +- Raw traces will appear in the result folder: `results/STEPS4`
```suggestion
- Raw traces will appear in the result folder: `raw_traces/STEPS4`
```

2022-05-09 08:15 UTC, cattabiani commented on validation/automated_validation_monitoring_results_displayer.ipynb
> +    "args =  f\"../../raw_traces/STEPS{steps_version} {ref_dir}\"\n",
this is the location where the traces are stored. It can be anywhere in the system. The place where we are running the notebook is more constrained and depends on where my python imports are. Running form STEPS_Validation is the simplest option IMHO

2022-05-11 14:21 UTC, kotsaloscv approved these changes

2022-05-11 14:21 UTC, merged