Automated Performance Monitoring (CI Integration) : WIP
CNS-OIST/STEPS4ModelRelease pull request #7
Opened 2022-04-06 08:08 UTC by kotsaloscv

Automated Performance Monitoring (CI Integration)

2022-04-06 08:17 UTC, cattabiani commented
do we need the `monitoring` in the name?

2022-04-06 08:18 UTC, kotsaloscv commented
> do we need the `monitoring` in the name?

I think yes :)

2022-04-06 08:20 UTC, cattabiani commented
ehm... why?

2022-04-06 08:26 UTC, kotsaloscv commented
because we monitor the performance by comparing the latest STEPS version with some reference commit.

2022-04-06 08:29 UTC, cattabiani commented
Isn't it already clear from the fact that it is in the CI? What is not `monitoring` but in the CI?

2022-04-06 12:05 UTC, tristan0x commented on SimpleModel/profiling/caliper.batch
> +source ./python-venv/bin/activate
This virtual environment is not mentioned in the documentation. If you really need to install additional Python packages, this sbatch should create it if missing.

```bash
[ -d python-venv ] || python3 -mvenv python-venv
source ./python-venv/bin/activate
pip install ...
```

2022-04-06 12:05 UTC, tristan0x commented on SimpleModel/profiling/caliper.batch
> +echo "SPACK_INSTALLED_HASH (steps) : " $SPACK_INSTALLED_HASH
This script should abort if:
* the `SPACK_INSTALLED_HASH` environment variable is not set.
* `spack find --paths /$SPACK_INSTALLED_HASH` cannot find the hash


I agree it should have been the case for` `SPACK_INSTALL_DIR` already...

2022-04-06 12:05 UTC, tristan0x commented on SimpleModel/profiling/caliper.batch
> -spack load caliper # or module load caliper, depending on your setup
I do not understand why the `caliper` module is not need anymore.

2022-05-19 08:13 UTC, cattabiani requested changes
I mostly changed my own stuff because I noted that it was not updated/wrong

2022-05-19 08:13 UTC, cattabiani commented on caBurst/background/extra/constants.py
> +#
also, I would try to put these constants in a class or something so they are easier to import. I had this problem when I wanted to structure a little bit more my code. An example: if you want to bring the main function of your simulation in a class member you cannot do `import constants` and getting these constants is clunky. 

It is probably material for a future PR

2022-05-19 08:13 UTC, cattabiani commented on profiling/README.md
> +Here, we describe how to perform the strong scaling & Roofline analysis found in STEPS 4 Release paper. To simply re-generate the graphs of the paper just run the `STEPS_PerfGraphs.ipynb` jupyter not
```suggestion
Here, we describe how to perform the strong scaling & Roofline analysis found in STEPS 4 Release paper. To simply re-generate the graphs of the paper just run the `STEPS_PerfGraphs.ipynb` jupyter notebook (all data is backed in).
```

2022-05-19 08:13 UTC, cattabiani commented on rallpack3/README.md
> +- Raw traces will appear in the result folder: `raw_traces/STEPS3`
```suggestion
`export mesh_file=mesh/axon_cube_L1000um_D866nm_1135tets.msh`
- Decide of you want to run with steps 3 or 4. For example:
`steps_version=4`
- Finally, run the command:
`python rallpack1_STEPS3.py ${rng_seed} ${mesh_file} ${steps_version}`
- Raw traces will appear in the result folder: `raw_traces/STEPS${steps_version}`
```

2022-05-19 08:13 UTC, cattabiani commented on rallpack3/README.md
> +## STEPS 3
```suggestion
```

2022-05-19 08:13 UTC, cattabiani commented on rallpack3/README.md
> +
```suggestion
```

2022-05-19 08:13 UTC, cattabiani commented on rallpack3/rallpack3.py
> +        sim = Simulation('DistTetOpSplit', mdl, mesh, rng)#, searchMethod=NextEventSearchMethod.GIBSON_BRUCK)
```suggestion
        sim = Simulation('DistTetOpSplit', mdl, mesh, rng, searchMethod=NextEventSearchMethod.GIBSON_BRUCK)
```

2022-05-19 08:13 UTC, cattabiani commented on rallpack3/rallpack3.py
> +        sim = Simulation('DistTetOpSplit', mdl, mesh, rng)#, searchMethod=NextEventSearchMethod.GIBSON_BRUCK)
this was an error that was going around for a long time

2022-05-19 08:15 UTC, kotsaloscv commented on SimpleModel/profiling/caliper.batch
> +echo "SPACK_INSTALLED_HASH (steps) : " $SPACK_INSTALLED_HASH
Fully agree & I have corrected it.

2022-05-19 08:15 UTC, kotsaloscv commented on SimpleModel/profiling/caliper.batch
> +source ./python-venv/bin/activate
The setup of the python virtual env is happening in the Jupyter notebook and this is why I am not checking at it any further.

2022-05-19 08:15 UTC, kotsaloscv commented on SimpleModel/profiling/caliper.batch
> -module purge
I had it in the past and I faced issues with the CI. This is why I removed it.
Any idea on how to activate it if not using the CI?

2022-05-20 13:14 UTC, tristan0x commented on SimpleModel/profiling/caliper.batch
> -module purge
You can test the presence of environment variable `CI_PIPELINE_ID`, or any other variable defined by GitLab CI https://docs.gitlab.com/ee/ci/variables/predefined_variables.html

2022-05-31 06:25 UTC, merged